server.port: 7888

spring:
 datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/training
  username: root
  password: hanhtd161
  hikari: 
   pool-name: training_pool
   maximum-pool-size: 10
   minimum-idle: 3
 application.name: training-jpa

logging:
 level:
  com.zaxxer.hikari: debug
  org.spring.transaction: debug  